import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import mainlogo from "../icon.png";
import { FaXTwitter } from "react-icons/fa6";
import { FaInstagram } from "react-icons/fa";
import { FaYoutube } from "react-icons/fa";
import { IoLogoLinkedin } from "react-icons/io5";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="flex justify-between border-b-1 m-10 border-solid border-gray-300 rounded-full p-1 px-1 mt-5">
          <div className="flex items-center gap-x-5">
            <Image src={mainlogo} alt="" />
            <div>SwapHub</div>
          </div>
          <div className="flex items-center gap-x-2">
            <Link
              href="/"
              className="bg-gray-100 hover:bg-blue-300 rounded-full p-1 px-1"
            >
              Listings
            </Link>
            <button className="hover:bg-blue-300 rounded-full p-1 px-1">
              Community
            </button>
            <Link
              href="/contact"
              className="hover:bg-blue-300 rounded-full p-1 px-1"
            >
              Contact
            </Link>
            <div className="flex gap-x-1 ml-4">
              <Link
                href="/sign-in"
                className="bg-gray-300 rounded-full p-1 px-1 hover:bg-blue-300"
              >
                Sign in
              </Link>
              <Link
                href="/sign-up"
                className="mx-8 bg-black text-white hover:bg-blue-300 rounded-full p-1 px-1"
              >
                Register
              </Link>
            </div>
          </div>
        </div>
        {children}
        <div className="flex justify-around border-t-1 m-10 border-solid border-gray-300 rounded-full p-1 px-1 pt-5">
          <div className="justify-between h-17">
            <div className="flex items-center gap-x-5">
              <Image src={mainlogo} alt="" />
              <div>SwapHub</div>
            </div>
            <div className="flex gap-x-3">
              <FaXTwitter />
              <FaInstagram />
              <FaYoutube />
              <IoLogoLinkedin />
            </div>
          </div>
          <div>
            <div className="font-bold mb-5">About SwapHub</div>
            <div>How it works</div>
            <div>Community guidelines</div>
            <div>Our mission</div>
            <div>Contact us</div>
          </div>
          <div>
            <div className="font-bold mb-5">Discover</div>
            <div>Browse categories</div>
            <div>Popular swaps</div>
            <div>Successful stories</div>
            <div>Upcoming events</div>
          </div>
          <div>
            <div className="font-bold mb-5">Support</div>
            <div>Help center</div>
            <div>FAQs</div>
            <div>Security tips</div>
            <div>Report an issue</div>
          </div>
        </div>
      </body>
    </html>
  );
}
